# This is a basic workflow to help you get started with Actions
#!/bin/bash
# WireGuard Shadowsocks V2Ray server-side three-in-one script short URL https://git.io/vps.sh

# Usage:  bash <(curl -L -s https://git.io/vps.sh)

# Install three-in-one by default Usage: wget -qO- git.io/vps.sh | bash
default_install(){

    # One-click install wireguard script
    wget -qO- git.io/fptwc | bash

    # V2Ray official one-click script
    bash <(curl -L -s https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)

    # One-click install shadowsocks-libev script
    wget -qO- git.io/fhExJ | bash

    # Install WireGuard+Speeder+Udp2Raw and SS+Kcp+Udp2RAW configuration
    bash wgmtu setup
}

display_conf(){
    echo
    echo
    echo_SkyBlue "# ======================================="
    echo_GreenBG "# V2ray server configuration/etc/v2ray/config.json"
    cat /etc/v2ray/config.json
    echo
    echo_SkyBlue "# WG+Speed+Udp2Raw 和 SS+Kcp+Udp2RAW 配置 /etc/rc.local"
    cat vps_setup.log
    echo_GreenBG "# WireGuard client configuration/etc/wireguard/client.conf"
    cat /etc/wireguard/client.conf
}

base_tools(){
    # Simplify the judgment system debian/centos ethnic group
    if [ -e '/etc/redhat-release' ]; then
        yum update -y && yum install -y  wget curl vim ca-certificates
    else
        apt update && apt install -y  wget curl vim  ca-certificates
    be
}

wget_curl(){
    if [[ ! -e /usr/bin/wget ]]; then
        base_tools
    be
    if [[ ! -e /usr/bin/curl ]]; then
        base_tools
    be
}

vps_remove(){
    bash <(curl -L -s https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh) --remove
    bash wgmtu remove
    cd /root && rm -f v2ray_ss.log vps_setup.log wg5 wgmtu /var/ip_addr /etc/v2ray/config.json \
        base64_shadowsocks.conf base64_v2ray_vmess.json
}

# setting menu
start_menu(){
    clear
    echo_GreenBG "> Open source project: https://github.com/hongwenjun/vps_setup "
    echo_SkyBlue "> 1. WireGuard Shadowsocks V2Ray server three-in-one is installed by default"
    echo_SkyBlue "> 2. Choose to install WireGuard multi-user server"
    echo_SkyBlue "> 3. Compile and install/update ${RedBG} shadowsocks-libev ${Font}"
    echo_SkyBlue "> 4. Uninstall the WireGuard Shadowsocks V2ray service program"
    echo         "-------------------------------------------------------"
    echo_Yellow "> 5. Display WireGuard V2ray and rc.local configuration information"
    echo_Yellow  ">  6. 退出"
    echo_Yellow "> 7. WireGuard management command ${RedBG} bash wgmtu "
    echo_Yellow "> 8. Choose to install ${GreenBG} Shadowsocks and V2Ray ${Yellow} Configure to display the QR code"
    echo_Yellow "> 9. Choose to install ${RedBG} Trojan for fools one-click version ${Yellow}"
    read -p "Please enter a number:" -t 30 num
    case "$num" in
        1)
        default_install
        ;;
        2)
        wget -qO- git.io/fptwc | bash
        ;;
        3)
        bash <(curl -L -s git.io/fhExJ) update
        ;;
        4)
        vps_remove
        ;;
        5)
        display_conf
        ;;
        6)
        exit 1
        ;;
        7)
        bash <(curl -L -s https://git.io/wgmtu)
        wget -O wgmtu https://git.io/wgmtu  >/dev/null 2>&1
        ;;
        8)
        bash <(curl -L -s https://git.io/v2ray.ss)
        ;;
        9)
        bash <(curl -L -s https://git.io/trojan.sh)
        ;;
        *)
        default_install
        ;;
        esac
}

# Display text color
Green="\033[32m"  && Red="\033[31m" && GreenBG="\033[42;37m" && RedBG="\033[41;37m"
Font="\033[0m"  && Yellow="\033[0;33m" && SkyBlue="\033[0;36m"

echo_SkyBlue(){
    echo -e "${SkyBlue}$1${Font}"
}
echo_Yellow(){
    echo -e "${Yellow}$1${Font}"
}
echo_GreenBG(){
    echo -e "${GreenBG}$1${Font}"
}

# Install wg ss v2 script start menu and necessary wget and curl tools
wget_curl
start_menu

